name: Terragrunt Check
description: "Runs Terragrunt check on specified environment"

runs:
  using: "composite"
  steps:
    - name: Check terragrunt HCL
      uses: gruntwork-io/terragrunt-action@v2
      with:
        tf_version: ${{ env.tf_version }}
        tg_version: ${{ env.tg_version }}
        tg_dir: ${{ env.working_dir }}
        tg_command: "hclfmt --terragrunt-check --terragrunt-diff"
