name: Terragrunt Apply
description: "Runs Terragrunt apply on specified environment"

runs:
  using: "composite"
  steps:
    - name: Deploy
      uses: gruntwork-io/terragrunt-action@v2
      with:
        tf_version: ${{ env.tf_version }}
        tg_version: ${{ env.tg_version }}
        tg_dir: ${{ env.working_dir }}
        tg_command: "run-all apply"
